#!/usr/bin/env python3
"""Write tokens.json and tokens.css: the Heron OS palette, the Aero glass recipe, and the type.

Run from the repository root:  python3 docs/brand/tools/build_tokens.py

The values are the ones docs/brand/README.md lists; the site's CSS in site/src/styles/ uses the same
values. build_assets.py reads COLOR from here to draw the mark, the favicon and the social preview.
"""
import json
from pathlib import Path

BRAND = Path(__file__).resolve().parent.parent

# The glass of the frame: a tint over whatever lies behind the window.
GLASS = {
    "active": "rgba(104, 150, 178, 0.42)",      # the frame of the focused window
    "inactive": "rgba(150, 178, 196, 0.28)",    # every other window frame
    "maximised": "rgba(28, 44, 56, 0.86)",      # a maximised frame, nearly opaque
    "edge": "rgba(0, 0, 0, 0.72)",              # the 1 px outer line of every frame
    "rim": "rgba(255, 255, 255, 0.5)",          # the 1 px inner highlight of every frame
}

# The opaque surfaces inside the frame, the ink on them, and the colours the mark is drawn in.
COLOR = {
    "surface": "#FFFFFF",
    "surface-pane": "#F2F7FB",
    "surface-footer": "#F0F0F0",
    "ink": "#000000",
    "ink-instruction": "#003399",
    "ink-heading": "#1E395B",
    "ink-section": "#1E5AA0",
    "ink-secondary": "#6D6D6D",
    "link": "#0066CC",
    "link-hover": "#3399FF",
    "select-border": "#84ACDD",
    "select-fill-top": "#F2F8FD",
    "select-fill-bottom": "#D9ECFD",
    "hover-border": "#B8D6FB",
    "command-bar-top": "#6798B3",
    "command-bar-bottom": "#25607F",
    # The Start orb's glass bead, which the favicon repeats.
    "orb-light": "#8FD0FF",
    "orb": "#2A79C9",
    "orb-deep": "#0D3D78",
    "orb-edge": "#0B3565",
    # The frame of a maximised window flattened on black, for the mark on dark places.
    "frame-dark": "#18262F",
    # The Aurora wallpaper's deep green and its brightest ribbon.
    "aurora-night": "#02140F",
    "aurora-deep": "#06332B",
    "aurora-ribbon": "#3FDC7C",
}

RIBBON = {
    "tab-top": "#E3EEFB", "tab-bottom": "#CFE1F7",
    "group-top": "#F4F8FE", "group-bottom": "#D1E2F6", "group-border": "#99BBE8",
    "label-ink": "#244C86", "label-fill": "#B7D0EE", "ink": "#15428B",
    "hover-top": "#FFFBE6", "hover-bottom": "#FFE89C",
    "pressed-top": "#FDE2B1", "pressed-bottom": "#FCD174",
}

# Example GitLab label colours for the four verdict labels, with white text. Heron sets the labels its config names.
LABEL = {
    "in progress": "#4C5391",
    "passed": "#2F6B55",
    "changes requested": "#7A5520",
    "blocked": "#9A3B3B",
}

# The five layers of an Aero glass frame, back to front, and the halo that keeps caption text legible.
RECIPE = {
    "blur": "blur(9px) saturate(1.45) brightness(1.02)",
    "gloss": "linear-gradient(to bottom, rgba(255, 255, 255, 0.42), rgba(255, 255, 255, 0.12) 28px, "
             "rgba(255, 255, 255, 0.04) 60%, rgba(255, 255, 255, 0.1))",
    "sheen": "linear-gradient(118deg, rgba(255, 255, 255, 0) 6%, rgba(255, 255, 255, 0.28) 10%, "
             "rgba(255, 255, 255, 0.08) 15%, rgba(255, 255, 255, 0) 19%), "
             "linear-gradient(118deg, rgba(255, 255, 255, 0) 28%, rgba(255, 255, 255, 0.2) 31%, rgba(255, 255, 255, 0) 36%), "
             "linear-gradient(118deg, rgba(255, 255, 255, 0) 52%, rgba(255, 255, 255, 0.18) 57%, "
             "rgba(255, 255, 255, 0.04) 65%, rgba(255, 255, 255, 0) 67%), "
             "linear-gradient(118deg, rgba(255, 255, 255, 0) 79%, rgba(255, 255, 255, 0.16) 83%, rgba(255, 255, 255, 0) 87%)",
    "shadow-active": "0 8px 30px rgba(0, 0, 0, 0.55)",
    "shadow-inactive": "0 4px 18px rgba(0, 0, 0, 0.42)",
    "caption-halo": "0 0 5px #FFFFFF, 0 0 9px rgba(255, 255, 255, 0.9), 0 0 14px rgba(255, 255, 255, 0.7)",
}

FONT = {
    "ui": "'Heron UI', 'Segoe UI', sans-serif",
    "mono": "'Lucida Console', Consolas, 'DejaVu Sans Mono', monospace",
    "diagram": "Arial, 'Heron UI', sans-serif",
}
SIZE = {"ribbon": "11px", "body": "12px", "section": "13px", "instruction": "16px", "page-title": "18px"}
WEIGHT = {"body": "400", "first-line": "600"}


def tokens_json():
    def group(values, kind):
        return {k: {"$value": v, "$type": kind} for k, v in values.items()}
    return {
        "$description": "Heron OS design tokens. Values follow the W3C Design Tokens draft shape: $value and $type.",
        "glass": group(GLASS, "color"),
        "color": group(COLOR, "color"),
        "ribbon": group(RIBBON, "color"),
        "label": group(LABEL, "color"),
        "recipe": {k: {"$value": v, "$type": "string"} for k, v in RECIPE.items()},
        "font": group(FONT, "fontFamily"),
        "size": group(SIZE, "dimension"),
        "weight": group(WEIGHT, "fontWeight"),
    }


def tokens_css():
    def lines(prefix, values):
        return [f"  --heron-{prefix}-{k.replace(' ', '-')}: {v};" for k, v in values.items()]
    out = ["/* Heron OS design tokens. Generated by docs/brand/tools/build_tokens.py. */", ":root {"]
    out += lines("glass", GLASS) + lines("color", COLOR) + lines("ribbon", RIBBON) + lines("label", LABEL)
    out += lines("recipe", RECIPE) + lines("font", FONT) + lines("size", SIZE) + lines("weight", WEIGHT)
    out += ["}", ""]
    return "\n".join(out)


if __name__ == "__main__":
    (BRAND / "tokens.json").write_text(json.dumps(tokens_json(), indent=2) + "\n")
    (BRAND / "tokens.css").write_text(tokens_css())
    print("tokens.json tokens.css")
