// Builds the Heron OS design book for the web. Reads docs/brand/README.md, regenerates its contrast
// table, and writes site/public/brand/index.html. Help and Support renders the same README in the site.
//
//   node docs/brand/tools/build_book.ts           write both files
//   node docs/brand/tools/build_book.ts --check   exit 1 if either file is out of date
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { type Block, type Inline, topicsOf } from "../../../site/src/apps/markdown.ts"

const brand = join(dirname(fileURLToPath(import.meta.url)), "..")
const repo = join(brand, "..", "..")
const readmePath = join(brand, "README.md")
const pagePath = join(repo, "site", "public", "brand", "index.html")

// ---- Contrast -------------------------------------------------------------------------------------

type Pair = readonly [use: string, text: string, background: string, rule: "text" | "exempt"]

/** Every text colour Heron OS sets, on the surface it sits on. Values come from site/src/styles. */
const pairs: ReadonlyArray<Pair> = [
  ["Body text on a client area", "#000000", "#FFFFFF", "text"],
  ["Main instruction", "#003399", "#FFFFFF", "text"],
  ["Pane titles and status bars", "#1E395B", "#FFFFFF", "text"],
  ["Section headings", "#1E5AA0", "#FFFFFF", "text"],
  ["Links", "#0066CC", "#FFFFFF", "text"],
  ["Column values and hints", "#6D6D6D", "#FFFFFF", "text"],
  ["Details pane labels", "#4C607A", "#FFFFFF", "text"],
  ["Welcome Center fact labels", "#4D6079", "#E2EEF9", "text"],
  ["Status bar text", "#1E395B", "#DDE6F0", "text"],
  ["Info bar text", "#000000", "#FFFFE1", "text"],
  ["Explorer command bar, upper half", "#FFFFFF", "#3D7593", "text"],
  ["Explorer command bar, lower half", "#FFFFFF", "#1F5775", "text"],
  ["Help toolbar", "#FFFFFF", "#346FAE", "text"],
  ["Ribbon text", "#15428B", "#C9DCF5", "text"],
  ["Ribbon group labels", "#244C86", "#B7D0EE", "text"],
  ["Diagram shape label", "#14233A", "#BCD4F0", "text"],
  ["Diagram shape sublabel", "#3F5270", "#BCD4F0", "text"],
  ["Phone selected row", "#FFFFFF", "#1F4EA8", "text"],
  ["Phone soft key", "#FFFFFF", "#2B5CB8", "text"],
  ["Label review::in progress", "#FFFFFF", "#4C5391", "text"],
  ["Label review::passed", "#FFFFFF", "#2F6B55", "text"],
  ["Label review::changes requested", "#FFFFFF", "#7A5520", "text"],
  ["Label review::blocked", "#FFFFFF", "#9A3B3B", "text"],
  ["Disabled button text", "#838383", "#F4F4F4", "exempt"],
]

const channel = (value: number): number => {
  const c = value / 255
  return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4
}

const luminance = (hex: string): number => {
  const [r, g, b] = [1, 3, 5].map((at) => channel(Number.parseInt(hex.slice(at, at + 2), 16)))
  return 0.2126 * (r ?? 0) + 0.7152 * (g ?? 0) + 0.0722 * (b ?? 0)
}

const ratio = (a: string, b: string): number => {
  const [high, low] = [luminance(a), luminance(b)].sort((x, y) => y - x)
  return ((high ?? 0) + 0.05) / ((low ?? 0) + 0.05)
}

const grade = (value: number, rule: Pair[3]): string =>
  rule === "exempt" ? "exempt" : value >= 7 ? "AAA" : value >= 4.5 ? "AA" : "FAIL"

const contrastTable = (): string => {
  const rows = pairs.map(([use, text, background, rule]) => {
    const value = ratio(text, background)
    return `| ${use} | \`${text}\` | \`${background}\` | ${value.toFixed(2)} | ${grade(value, rule)} |`
  })
  return ["| Use | Text | Background | Ratio | WCAG |", "|---|---|---|---|---|", ...rows].join("\n")
}

const failing = pairs.filter(([, text, background, rule]) => rule === "text" && ratio(text, background) < 4.5)
if (failing.length > 0) {
  console.error(`contrast below AA: ${failing.map(([use]) => use).join(", ")}`)
  process.exit(1)
}

const start = "<!-- contrast-table:start (generated by docs/brand/tools/build_book.ts) -->"
const end = "<!-- contrast-table:end -->"

const withTable = (source: string): string => {
  const from = source.indexOf(start)
  const to = source.indexOf(end)
  if (from < 0 || to < from) throw new Error("README.md has lost its contrast-table markers")
  return `${source.slice(0, from + start.length)}\n\n${contrastTable()}\n\n${source.slice(to)}`
}

// ---- HTML -----------------------------------------------------------------------------------------

const escape = (text: string): string =>
  text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;")

const isColour = (text: string): boolean => /^#[0-9a-f]{6}$/i.test(text) || /^rgba?\([\d\s.,]+\)$/.test(text)

const inline = (parts: ReadonlyArray<Inline>): string =>
  parts
    .map((part) => {
      switch (part.kind) {
        case "text":
          return escape(part.text)
        case "code":
          return isColour(part.text)
            ? `<code><span class="swatch" style="background:${escape(part.text)}"></span>${escape(part.text)}</code>`
            : `<code>${escape(part.text)}</code>`
        case "strong":
          return `<strong>${escape(part.text)}</strong>`
        case "link":
          return `<a href="${escape(part.href)}">${escape(part.text)}</a>`
      }
    })
    .join("")

const block = (item: Block): string => {
  switch (item.kind) {
    case "heading":
      return `<h3>${inline(item.text)}</h3>`
    case "paragraph":
      return `<p>${inline(item.text)}</p>`
    case "list": {
      const tag = item.isOrdered ? "ol" : "ul"
      return `<${tag}>${item.items.map((each) => `<li>${inline(each)}</li>`).join("")}</${tag}>`
    }
    case "table":
      return `<div class="table"><table><thead><tr>${item.head.map((cell) => `<th>${inline(cell)}</th>`).join("")}</tr></thead><tbody>${item.rows
        .map((row) => `<tr>${row.map((cell) => `<td>${inline(cell)}</td>`).join("")}</tr>`)
        .join("")}</tbody></table></div>`
    case "code":
      return `<pre>${escape(item.text)}</pre>`
  }
}

const style = `
@font-face{font-family:"Heron UI";src:local("Segoe UI"),local("SegoeUI"),url(../fonts/heron-sans-regular.woff2) format("woff2");font-weight:400;font-display:swap}
@font-face{font-family:"Heron UI";src:local("Segoe UI Semibold"),local("SegoeUI-Semibold"),url(../fonts/heron-sans-semibold.woff2) format("woff2");font-weight:600;font-display:swap}
:root{color-scheme:light}
*{box-sizing:border-box}
body{margin:0;background:linear-gradient(#dfeaf5,#f4f8fc 320px) no-repeat,#f4f8fc;color:#000;font:14px/1.55 "Heron UI","Segoe UI",sans-serif}
a{color:#0066cc}a:hover{color:#3399ff}
.bar{display:flex;align-items:center;gap:12px;padding:10px 24px;color:#fff;background:linear-gradient(#5f95cf,#346fae 48%,#255e9c 50%,#2f69a8);border-bottom:1px solid #0c2a3d}
.bar img{width:28px;height:28px}.bar strong{font-weight:400;font-size:16px}.bar span{opacity:.9}
.bar a{margin-left:auto;color:#fff}
.wrap{display:grid;grid-template-columns:230px minmax(0,760px);gap:28px;max-width:1080px;margin:0 auto;padding:24px}
nav{position:sticky;top:16px;align-self:start;padding:12px 8px;background:#fff;border:1px solid #cfdbe9;border-radius:4px}
nav h2{margin:0 0 6px 8px;font-size:12px;color:#1e395b}
nav a{display:block;padding:3px 8px;border:1px solid transparent;border-radius:3px;text-decoration:none}
nav a:hover{border-color:#b8d6fb;background:linear-gradient(#fafcfe,#ebf3fd)}
main{background:#fff;border:1px solid #cfdbe9;border-radius:4px;padding:8px 32px 32px}
section{padding-top:8px}
h1{font-size:26px;font-weight:400;color:#1e5aa0;margin:16px 0 8px}
h2{font-size:20px;font-weight:400;color:#1e5aa0;margin:28px 0 10px;padding-bottom:6px;border-bottom:1px solid #d9e5f2}
h3{font-size:15px;font-weight:600;color:#1e395b;margin:20px 0 6px}
code{font:12.5px "Lucida Console",Consolas,"DejaVu Sans Mono",monospace;background:#eef2f7;padding:0 3px;border-radius:2px}
.swatch{display:inline-block;width:11px;height:11px;margin-right:4px;vertical-align:-1px;border:1px solid rgba(0,0,0,.35);border-radius:2px}
pre{font:12.5px/1.5 "Lucida Console",Consolas,"DejaVu Sans Mono",monospace;background:#f5f7fa;border:1px solid #dde4ec;padding:10px 12px;white-space:pre-wrap}
.table{overflow-x:auto;margin:0 0 14px}
table{border-collapse:collapse;font-size:13px}
th,td{padding:5px 9px;border:1px solid #cfdbe9;text-align:left;vertical-align:top}
th{font-weight:600;color:#1e395b;background:linear-gradient(#f6f9fd,#e6eef8)}
@media (max-width:760px){.wrap{grid-template-columns:1fr;padding:12px}nav{position:static}main{padding:4px 16px 20px}}
`.trim()

const page = (source: string): string => {
  const topics = topicsOf(source)
  const [home, ...rest] = topics
  const sections = rest
    .map((topic) => `<section id="${topic.id}"><h2>${escape(topic.title)}</h2>${topic.blocks.map(block).join("\n")}</section>`)
    .join("\n")
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Heron OS design book</title>
<meta name="description" content="How Heron OS, the public site of the Heron code-review bot, looks, sounds and speaks.">
<link rel="icon" href="assets/favicon.svg" type="image/svg+xml">
<style>${style}</style>
</head>
<body>
<header class="bar"><img src="assets/heron-mark-mono-white.svg" alt=""><strong>Heron OS Help and Support</strong><span>Design book</span><a href="../">Open Heron OS</a></header>
<div class="wrap">
<nav aria-label="Contents"><h2>Contents</h2>${rest.map((topic) => `<a href="#${topic.id}">${escape(topic.title)}</a>`).join("")}</nav>
<main>
<h1>${escape(home?.title ?? "Heron OS design book")}</h1>
${(home?.blocks ?? []).map(block).join("\n")}
${sections}
</main>
</div>
</body>
</html>
`
}

// ---- Write or check -------------------------------------------------------------------------------

const readme = withTable(readFileSync(readmePath, "utf8"))
const html = page(readme)
const isCheck = process.argv.includes("--check")
const stale = [
  [readmePath, readme],
  [pagePath, html],
].filter(([path, content]) => readFileSync(path ?? "", "utf8") !== content)

if (isCheck) {
  if (stale.length > 0) {
    console.error(`out of date: ${stale.map(([path]) => path).join(", ")}. Run node docs/brand/tools/build_book.ts`)
    process.exit(1)
  }
  console.log("design book is up to date")
} else {
  writeFileSync(readmePath, readme)
  writeFileSync(pagePath, html)
  console.log(`wrote ${readmePath} and ${pagePath}`)
}
