/**
 * Renders the environment-variable table in docs/configuration.md from `envVars` in src/config.ts.
 *
 *   node scripts/gen-env-table.ts          rewrite the table in place
 *   node scripts/gen-env-table.ts --check  exit 1 when the table differs from `envVars`
 */
import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { envVars } from "../src/config.ts"

export const DOC = fileURLToPath(new URL("../docs/configuration.md", import.meta.url))
export const START = "<!-- env-table:start (generated by scripts/gen-env-table.ts) -->"
export const END = "<!-- env-table:end -->"

const cell = (text: string) => text.replace(/\|/g, "\\|")

export const envTable = (): string =>
  [
    "| Variable | Config key | Kind | Meaning |",
    "| --- | --- | --- | --- |",
    ...envVars.map((v) =>
      `| \`${v.name}\` | ${v.target === null ? "none" : `\`${v.target.join(".")}\``} | ${v.kind} | ${cell(v.description)} |`
    )
  ].join("\n")

/** The text between the markers, or null when a marker is missing. */
export const tableIn = (doc: string): string | null => {
  const start = doc.indexOf(START)
  const end = doc.indexOf(END)
  return start < 0 || end < start ? null : doc.slice(start + START.length, end).trim()
}

const main = (check: boolean) => {
  const doc = readFileSync(DOC, "utf8")
  const current = tableIn(doc)
  if (current === null) {
    console.error(`${DOC}: missing ${START} or ${END}`)
    process.exitCode = 1
    return
  }
  const wanted = envTable()
  if (current === wanted) return
  if (check) {
    console.error("docs/configuration.md: the environment table is out of date; run pnpm gen-env-table")
    process.exitCode = 1
    return
  }
  const start = doc.indexOf(START) + START.length
  writeFileSync(DOC, `${doc.slice(0, start)}\n\n${wanted}\n\n${doc.slice(doc.indexOf(END))}`)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main(process.argv.includes("--check"))
